#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Concesionario_LinqXml
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ConcesionarioLinqXml")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertVehiculos(Vehiculos instance);
    partial void UpdateVehiculos(Vehiculos instance);
    partial void DeleteVehiculos(Vehiculos instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Concesionario_LinqXml.Properties.Settings.Default.ConcesionarioLinqXmlConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Vehiculos> Vehiculos
		{
			get
			{
				return this.GetTable<Vehiculos>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Vehiculos")]
	public partial class Vehiculos : INotifyPropertyChanging, INotifyPropertyChanged, IEquatable<Vehiculos>
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Marca;
		
		private string _Modelo;
		
		private string _Version;
		
		private string _Color;
		
		private string _Precio;
		
		private string _Combustible;
		
		private string _Foto;
		
		private string _Ex1;
		
		private string _Ex2;
		
		private string _Ex3;
		
		private string _Ex4;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnModeloChanging(string value);
    partial void OnModeloChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnPrecioChanging(string value);
    partial void OnPrecioChanged();
    partial void OnCombustibleChanging(string value);
    partial void OnCombustibleChanged();
    partial void OnFotoChanging(string value);
    partial void OnFotoChanged();
    partial void OnEx1Changing(string value);
    partial void OnEx1Changed();
    partial void OnEx2Changing(string value);
    partial void OnEx2Changed();
    partial void OnEx3Changing(string value);
    partial void OnEx3Changed();
    partial void OnEx4Changing(string value);
    partial void OnEx4Changed();
    #endregion
		
		public Vehiculos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="VarChar(50)")]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modelo", DbType="VarChar(50)")]
		public string Modelo
		{
			get
			{
				return this._Modelo;
			}
			set
			{
				if ((this._Modelo != value))
				{
					this.OnModeloChanging(value);
					this.SendPropertyChanging();
					this._Modelo = value;
					this.SendPropertyChanged("Modelo");
					this.OnModeloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="VarChar(50)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="VarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="VarChar(50)")]
		public string Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Combustible", DbType="VarChar(50)")]
		public string Combustible
		{
			get
			{
				return this._Combustible;
			}
			set
			{
				if ((this._Combustible != value))
				{
					this.OnCombustibleChanging(value);
					this.SendPropertyChanging();
					this._Combustible = value;
					this.SendPropertyChanged("Combustible");
					this.OnCombustibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Foto", DbType="VarChar(50)")]
		public string Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				if ((this._Foto != value))
				{
					this.OnFotoChanging(value);
					this.SendPropertyChanging();
					this._Foto = value;
					this.SendPropertyChanged("Foto");
					this.OnFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ex1", DbType="VarChar(50)")]
		public string Ex1
		{
			get
			{
				return this._Ex1;
			}
			set
			{
				if ((this._Ex1 != value))
				{
					this.OnEx1Changing(value);
					this.SendPropertyChanging();
					this._Ex1 = value;
					this.SendPropertyChanged("Ex1");
					this.OnEx1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ex2", DbType="VarChar(50)")]
		public string Ex2
		{
			get
			{
				return this._Ex2;
			}
			set
			{
				if ((this._Ex2 != value))
				{
					this.OnEx2Changing(value);
					this.SendPropertyChanging();
					this._Ex2 = value;
					this.SendPropertyChanged("Ex2");
					this.OnEx2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ex3", DbType="NChar(10)")]
		public string Ex3
		{
			get
			{
				return this._Ex3;
			}
			set
			{
				if ((this._Ex3 != value))
				{
					this.OnEx3Changing(value);
					this.SendPropertyChanging();
					this._Ex3 = value;
					this.SendPropertyChanged("Ex3");
					this.OnEx3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ex4", DbType="NChar(10)")]
		public string Ex4
		{
			get
			{
				return this._Ex4;
			}
			set
			{
				if ((this._Ex4 != value))
				{
					this.OnEx4Changing(value);
					this.SendPropertyChanging();
					this._Ex4 = value;
					this.SendPropertyChanged("Ex4");
					this.OnEx4Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

        public bool Equals(Vehiculos other)
        {
			return this.Modelo== other.Modelo;
        }
		public int GetHashCode(Vehiculos obj)
		{
			return obj.Modelo.GetHashCode();
		}
	}
}
#pragma warning restore 1591
